#!/usr/bin/env python3
"""
Automate SAML SSO Setup Steps
Provides automated assistance for SAML SSO setup where possible
#JARVIS #MANUS #NAS #SSO #SAML #AUTOMATION
"""

import sys
from pathlib import Path
from typing import Dict, Any, List
import logging
import json

project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

try:
    from lumina_logger import get_logger
except ImportError:
    logging.basicConfig(level=logging.INFO)
    get_logger = lambda name: logging.getLogger(name)

try:
    from synology_api_base import SynologyAPIBase
    from nas_azure_vault_integration import NASAzureVaultIntegration
    API_AVAILABLE = True
except ImportError:
    API_AVAILABLE = False

logger = get_logger("AutomateSSOSetup")


class SSOSetupAutomation:
    """Automate SAML SSO setup steps where possible"""

    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.nas_ip = "<NAS_PRIMARY_IP>"
        self.nas_port = 5001
        self.api: SynologyAPIBase = None

    def check_sso_server_installed(self) -> Dict[str, Any]:
        """Check if SSO Server package is installed"""
        if not API_AVAILABLE:
            return {
                "success": False,
                "error": "API not available"
            }

        try:
            self.api = SynologyAPIBase(nas_ip=self.nas_ip, nas_port=self.nas_port)

            # Get credentials
            vault = NASAzureVaultIntegration()
            credentials = vault.get_nas_credentials()

            if not self.api.login(credentials["username"], credentials["password"]):
                return {
                    "success": False,
                    "error": "Login failed"
                }

            # Check packages
            data = self.api.api_call(
                api="SYNO.Core.Package",
                method="list",
                version="1",
                require_auth=True
            )

            self.api.logout()

            if data:
                packages = data.get("packages", [])
                sso_packages = [p for p in packages if "sso" in p.get("name", "").lower() or "sso" in p.get("display_name", "").lower()]

                return {
                    "success": True,
                    "installed": len(sso_packages) > 0,
                    "packages": sso_packages,
                    "all_packages": [p.get("name") for p in packages]
                }

            return {
                "success": False,
                "error": "Could not retrieve package list"
            }

        except Exception as e:
            logger.error(f"Error checking SSO Server: {e}")
            return {
                "success": False,
                "error": str(e)
            }

    def generate_azure_app_config(self) -> Dict[str, Any]:
        """Generate Azure AD app registration configuration"""
        config = {
            "app_name": "Synology DSM SSO",
            "identifier_uris": [
                "https://synology-dsm.local",
                "https://dsm.local"
            ],
            "reply_urls": [
                f"https://{self.nas_ip}:5001/portal/sso/acs",
                f"https://{self.nas_ip}:5001/webapi/auth.cgi"
            ],
            "required_permissions": [
                "User.Read",
                "openid",
                "profile",
                "email"
            ],
            "saml_settings": {
                "entity_id": f"https://{self.nas_ip}:5001",
                "assertion_consumer_service_url": f"https://{self.nas_ip}:5001/portal/sso/acs",
                "single_logout_service_url": f"https://{self.nas_ip}:5001/portal/sso/sls"
            },
            "note": "You'll need a verified domain in Azure AD. If you don't have one, use a placeholder URL and update after domain verification."
        }

        return {
            "success": True,
            "config": config
        }

    def create_setup_script(self) -> Path:
        """Create a setup script with all steps"""
        script_content = f"""#!/bin/bash
# Synology SAML SSO Setup Script
# Generated by JARVIS SSO Setup Automation

NAS_IP="{self.nas_ip}"
NAS_PORT="{self.nas_port}"

echo "=========================================="
echo "Synology SAML SSO Setup"
echo "=========================================="
echo ""

# Step 1: Check SSO Server package
echo "Step 1: Checking SSO Server package..."
echo "   Open DSM: https://$NAS_IP:$NAS_PORT"
echo "   Go to: Package Center"
echo "   Search for: 'SSO Server'"
echo "   Install if not installed"
echo ""
read -p "Press Enter when SSO Server is installed..."

# Step 2: Configure SSO Server as IdP
echo ""
echo "Step 2: Configure SSO Server"
echo "   Open: SSO Server application"
echo "   Go to: Identity Provider tab"
echo "   Enable: 'Enable SSO Server as Identity Provider'"
echo "   Note the Entity ID and SSO URL"
echo ""
read -p "Press Enter when configured..."

# Step 3: Azure AD App Registration
echo ""
echo "Step 3: Create Azure AD Enterprise Application"
echo "   Open: https://portal.azure.com"
echo "   Go to: Azure Active Directory > Enterprise applications"
echo "   Click: New application > Create your own application"
echo "   Name: Synology DSM SSO"
echo "   Type: Integrate any other application you don't find in the gallery"
echo ""
echo "   After creation:"
echo "   1. Go to Single sign-on > SAML"
echo "   2. Configure basic SAML settings"
echo "   3. Use Entity ID and SSO URL from Step 2"
echo ""
read -p "Press Enter when Azure app is created..."

# Step 4: Configure SAML in Azure
echo ""
echo "Step 4: Configure SAML in Azure AD"
echo "   In Azure AD Enterprise Application:"
echo "   1. Download Federation Metadata XML"
echo "   2. Note the Login URL and Azure AD Identifier"
echo ""
read -p "Press Enter when SAML is configured in Azure..."

# Step 5: Configure DSM SSO Client
echo ""
echo "Step 5: Configure DSM SSO Client"
echo "   In DSM SSO Server:"
echo "   1. Go to Service Provider tab"
echo "   2. Add new service provider"
echo "   3. Upload Federation Metadata XML from Azure"
echo "   4. Configure Entity ID and ACS URL"
echo ""
read -p "Press Enter when DSM is configured..."

# Step 6: Assign users
echo ""
echo "Step 6: Assign users in Azure AD"
echo "   In Azure AD Enterprise Application:"
echo "   1. Go to Users and groups"
echo "   2. Add users/groups who should have access"
echo ""
read -p "Press Enter when users are assigned..."

# Step 7: Test
echo ""
echo "Step 7: Test SSO"
echo "   Log out of DSM"
echo "   Try to log in - should redirect to Azure AD"
echo "   After Azure AD login, should redirect back to DSM"
echo ""
echo "✅ Setup complete!"
"""

        script_file = self.project_root / "scripts" / "nas" / "sso" / "setup_saml_sso.sh"
        script_file.parent.mkdir(parents=True, exist_ok=True)

        with open(script_file, 'w') as f:
            f.write(script_content)

        # Make executable (Unix)
        import os
        os.chmod(script_file, 0o755)

        logger.info(f"✅ Created setup script: {script_file}")
        return script_file

    def generate_azure_cli_commands(self) -> Dict[str, Any]:
        """Generate Azure CLI commands for app registration"""
        commands = {
            "create_app": f"""az ad app create \\
  --display-name "Synology DSM SSO" \\
  --identifier-uris "https://synology-dsm.local" \\
  --web-redirect-uris "https://{self.nas_ip}:5001/portal/sso/acs" """,

            "create_service_principal": """az ad sp create --id <app-id>""",

            "configure_saml": """# Note: SAML configuration must be done via Azure Portal
# Azure CLI doesn't support SAML configuration directly
# Use: https://portal.azure.com > Enterprise Applications > Your App > Single sign-on > SAML""",

            "assign_user": """az ad app owner add \\
  --id <app-id> \\
  --owner-object-id <user-object-id>"""
        }

        return {
            "success": True,
            "commands": commands,
            "note": "Some steps require Azure Portal (SAML configuration)"
        }

    def create_complete_guide(self) -> Path:
        """Create a complete setup guide with all information"""
        guide_content = f"""# Synology SAML SSO Complete Setup Guide

## Prerequisites

- Synology DSM access: https://{self.nas_ip}:{self.nas_port}
- Azure AD access: https://portal.azure.com
- Admin privileges on both systems

## Step-by-Step Setup

### Step 1: Install SSO Server Package

1. Open DSM: https://{self.nas_ip}:{self.nas_port}
2. Go to **Package Center**
3. Search for **"SSO Server"**
4. Click **Install**
5. Wait for installation to complete

### Step 2: Configure SSO Server as Identity Provider

1. Open **SSO Server** application in DSM
2. Go to **Identity Provider** tab
3. Enable **"Enable SSO Server as Identity Provider"**
4. Note the following (you'll need these for Azure):
   - **Entity ID**: (shown in SSO Server)
   - **SSO URL**: (shown in SSO Server)
   - **Certificate**: Download the certificate

### Step 3: Create Azure AD Enterprise Application

#### Option A: Via Azure Portal (Recommended)

1. Go to: https://portal.azure.com
2. Navigate to: **Azure Active Directory** > **Enterprise applications**
3. Click: **New application**
4. Click: **Create your own application**
5. Enter:
   - **Name**: Synology DSM SSO
   - **Type**: Integrate any other application you don't find in the gallery
6. Click **Create**

#### Option B: Via Azure CLI

```bash
# Create app registration
az ad app create \\
  --display-name "Synology DSM SSO" \\
  --identifier-uris "https://synology-dsm.local"

# Get app ID
APP_ID=$(az ad app list --display-name "Synology DSM SSO" --query "[0].appId" -o tsv)

# Create service principal
az ad sp create --id $APP_ID
```

**Note**: You'll need a verified domain in Azure AD. If you don't have one:
- Use a placeholder URL (e.g., `https://synology-dsm.local`)
- Verify your domain later
- Update the identifier URI after verification

### Step 4: Configure SAML in Azure AD

1. In your Enterprise Application, go to **Single sign-on**
2. Select **SAML**
3. Click **Edit** on Basic SAML Configuration
4. Enter:
   - **Identifier (Entity ID)**: From Step 2 (SSO Server Entity ID)
   - **Reply URL (Assertion Consumer Service URL)**: `https://{self.nas_ip}:5001/portal/sso/acs`
   - **Sign on URL**: From Step 2 (SSO Server SSO URL)
5. Click **Save**
6. Download **Federation Metadata XML** (you'll need this for DSM)

### Step 5: Configure DSM SSO Client

1. In DSM, open **SSO Server**
2. Go to **Service Provider** tab
3. Click **Add**
4. Select **Import from metadata file**
5. Upload the **Federation Metadata XML** from Azure AD
6. Configure:
   - **Entity ID**: From Azure AD (Identifier/Entity ID)
   - **ACS URL**: `https://{self.nas_ip}:5001/portal/sso/acs`
7. Click **Save**

### Step 6: Assign Users in Azure AD

1. In Azure AD Enterprise Application, go to **Users and groups**
2. Click **Add user/group**
3. Select users or groups who should have access to DSM
4. Click **Assign**

### Step 7: Test SSO

1. Log out of DSM
2. Try to log in
3. You should be redirected to Azure AD login
4. After successful Azure AD login, you should be redirected back to DSM
5. You should be logged in automatically

## Troubleshooting

### Issue: "Incorrect Authorization information"
- **Solution**: Check that username format matches Azure AD (usually `username@domain.com`)

### Issue: Redirect loop
- **Solution**: Verify ACS URL matches exactly in both Azure AD and DSM

### Issue: Certificate errors
- **Solution**: Ensure certificates are properly configured in both systems

## Configuration Files

- Azure AD App Config: See `azure_app_config.json` (generated)
- Setup Script: `scripts/nas/sso/setup_saml_sso.sh`

## Next Steps After Setup

1. Test SSO login flow
2. Configure user mapping (if needed)
3. Set up group-based access (optional)
4. Document the setup for team reference
"""

        guide_file = self.project_root / "docs" / "system" / "SAML_SSO_COMPLETE_SETUP.md"
        guide_file.parent.mkdir(parents=True, exist_ok=True)

        with open(guide_file, 'w') as f:
            f.write(guide_content)

        logger.info(f"✅ Created complete guide: {guide_file}")
        return guide_file

    def run_all_automation(self) -> Dict[str, Any]:
        try:
            """Run all automation steps"""
            results = {
                "success": True,
                "steps_completed": [],
                "steps_pending": [],
                "files_created": []
            }

            # Step 1: Check SSO Server
            logger.info("Step 1: Checking SSO Server installation...")
            sso_check = self.check_sso_server_installed()
            if sso_check.get("success"):
                if sso_check.get("installed"):
                    results["steps_completed"].append("SSO Server is installed")
                    logger.info("✅ SSO Server is installed")
                else:
                    results["steps_pending"].append("Install SSO Server package in DSM")
                    logger.warning("⚠️  SSO Server not installed - manual step required")
            else:
                results["steps_pending"].append("Check SSO Server installation (manual)")
                logger.warning("⚠️  Could not check SSO Server status")

            # Step 2: Generate Azure app config
            logger.info("Step 2: Generating Azure AD app configuration...")
            azure_config = self.generate_azure_app_config()
            if azure_config.get("success"):
                config_file = self.project_root / "config" / "azure_ad_sso_config.json"
                config_file.parent.mkdir(parents=True, exist_ok=True)
                with open(config_file, 'w') as f:
                    json.dump(azure_config["config"], f, indent=2)
                results["files_created"].append(str(config_file))
                results["steps_completed"].append("Azure AD app config generated")
                logger.info(f"✅ Azure config saved: {config_file}")

            # Step 3: Generate Azure CLI commands
            logger.info("Step 3: Generating Azure CLI commands...")
            cli_commands = self.generate_azure_cli_commands()
            if cli_commands.get("success"):
                commands_file = self.project_root / "scripts" / "nas" / "sso" / "azure_cli_commands.sh"
                commands_file.parent.mkdir(parents=True, exist_ok=True)
                with open(commands_file, 'w') as f:
                    f.write("#!/bin/bash\n# Azure CLI commands for SSO setup\n\n")
                    for cmd_name, cmd in cli_commands["commands"].items():
                        f.write(f"# {cmd_name}\n{cmd}\n\n")
                import os
                os.chmod(commands_file, 0o755)
                results["files_created"].append(str(commands_file))
                results["steps_completed"].append("Azure CLI commands generated")
                logger.info(f"✅ CLI commands saved: {commands_file}")

            # Step 4: Create setup script
            logger.info("Step 4: Creating interactive setup script...")
            setup_script = self.create_setup_script()
            results["files_created"].append(str(setup_script))
            results["steps_completed"].append("Setup script created")

            # Step 5: Create complete guide
            logger.info("Step 5: Creating complete setup guide...")
            guide = self.create_complete_guide()
            results["files_created"].append(str(guide))
            results["steps_completed"].append("Complete guide created")

            return results


        except Exception as e:
            self.logger.error(f"Error in run_all_automation: {e}", exc_info=True)
            raise
def main():
    try:
        """CLI interface"""
        import argparse
        import json

        parser = argparse.ArgumentParser(description="Automate SAML SSO Setup Steps")
        parser.add_argument("--check-sso", action="store_true", help="Check if SSO Server is installed")
        parser.add_argument("--generate-all", action="store_true", help="Generate all automation files")
        parser.add_argument("--json", action="store_true", help="Output as JSON")

        args = parser.parse_args()

        automation = SSOSetupAutomation(project_root)

        if args.generate_all:
            result = automation.run_all_automation()
        elif args.check_sso:
            result = automation.check_sso_server_installed()
        else:
            result = automation.run_all_automation()

        if args.json:
            print(json.dumps(result, indent=2))
        else:
            print("=" * 70)
            print("   SAML SSO SETUP AUTOMATION")
            print("=" * 70)
            print("")

            if isinstance(result, dict) and "steps_completed" in result:
                print("✅ Completed Steps:")
                for step in result.get("steps_completed", []):
                    print(f"   • {step}")
                print("")

                if result.get("steps_pending"):
                    print("⏳ Pending Steps (Manual):")
                    for step in result.get("steps_pending", []):
                        print(f"   • {step}")
                    print("")

                if result.get("files_created"):
                    print("📄 Files Created:")
                    for file in result.get("files_created", []):
                        print(f"   • {file}")
            else:
                if result.get("success"):
                    if result.get("installed"):
                        print("✅ SSO Server is installed")
                        if result.get("packages"):
                            print("\n📦 SSO Packages:")
                            for pkg in result["packages"]:
                                print(f"   • {pkg.get('name', 'Unknown')}")
                    else:
                        print("⚠️  SSO Server not installed")
                        print("   Install via: Package Center > SSO Server")
                else:
                    print(f"❌ Error: {result.get('error', 'Unknown error')}")
                    return 1

        return 0 if result.get("success") else 1


    except Exception as e:
        logger.error(f"Error in main: {e}", exc_info=True)
        raise
if __name__ == "__main__":


    sys.exit(main())