#!/usr/bin/env python3
"""
Global Keyboard Shortcuts for Windows - @ASK Integration

Maps keyboard shortcuts globally across Windows OS and all applications.
Integrates with @ASK command for universal keyboard shortcut management.

Tags: #KEYBOARD_SHORTCUTS #WINDOWS #GLOBAL #ASK #PRODUCTIVITY @JARVIS @LUMINA
"""

import sys
import json
import subprocess
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime
import logging

script_dir = Path(__file__).parent
project_root = script_dir.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
if str(script_dir) not in sys.path:
    sys.path.insert(0, str(script_dir))

try:
    from lumina_logger import get_logger
except ImportError:
    logging.basicConfig(level=logging.INFO)
    get_logger = lambda name: logging.getLogger(name)

logger = get_logger("GlobalKeyboardShortcutsWindows")


class GlobalKeyboardShortcutsWindows:
    """
    Global Keyboard Shortcuts for Windows

    Maps keyboard shortcuts globally across Windows OS and all applications.
    Integrates with @ASK command.
    """

    def __init__(self, project_root: Optional[Path] = None):
        """Initialize global keyboard shortcuts system"""
        if project_root is None:
            project_root = Path(__file__).parent.parent.parent

        self.project_root = Path(project_root)
        self.data_dir = self.project_root / "data" / "global_keyboard_shortcuts"
        self.data_dir.mkdir(parents=True, exist_ok=True)

        self.config_file = self.project_root / "config" / "global_keyboard_shortcuts.json"
        self.shortcuts = self._load_shortcuts()

        logger.info("✅ Global Keyboard Shortcuts Windows initialized")
        logger.info("   @ASK integration: ACTIVE")

    def _load_shortcuts(self) -> Dict[str, Any]:
        """Load keyboard shortcuts configuration"""
        try:
            if self.config_file.exists():
                with open(self.config_file, 'r', encoding='utf-8') as f:
                    return json.load(f)
        except Exception as e:
            logger.warning(f"   ⚠️  Could not load shortcuts config: {e}")

        return {
            "version": "1.0.0",
            "shortcuts": [],
            "cursor_ide": {},
            "windows_global": {},
            "application_specific": {}
        }

    def _save_shortcuts(self):
        """Save keyboard shortcuts configuration"""
        try:
            with open(self.config_file, 'w', encoding='utf-8') as f:
                json.dump(self.shortcuts, f, indent=2, ensure_ascii=False)
        except Exception as e:
            logger.error(f"   ❌ Error saving shortcuts: {e}")

    def register_cursor_shortcuts(self, shortcuts: Dict[str, str]) -> Dict[str, Any]:
        """
        Register Cursor IDE keyboard shortcuts

        Args:
            shortcuts: Dictionary of command -> key mapping

        Returns:
            Registration result
        """
        logger.info("📋 Registering Cursor IDE keyboard shortcuts")
        logger.info("")

        if "cursor_ide" not in self.shortcuts:
            self.shortcuts["cursor_ide"] = {}

        registered = []
        for command, key in shortcuts.items():
            self.shortcuts["cursor_ide"][command] = key
            registered.append({"command": command, "key": key})
            logger.info(f"   ✅ {command}: {key}")

        self._save_shortcuts()
        logger.info("")

        return {
            "registered": registered,
            "total": len(registered)
        }

    def register_windows_global_shortcuts(self, shortcuts: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
        """
        Register Windows global keyboard shortcuts (AutoHotkey script)

        Args:
            shortcuts: Dictionary of key -> action mapping

        Returns:
            Registration result
        """
        logger.info("📋 Registering Windows global keyboard shortcuts")
        logger.info("")

        if "windows_global" not in self.shortcuts:
            self.shortcuts["windows_global"] = {}

        registered = []
        for key, action in shortcuts.items():
            self.shortcuts["windows_global"][key] = action
            registered.append({"key": key, "action": action})
            logger.info(f"   ✅ {key}: {action.get('description', 'N/A')}")

        self._save_shortcuts()
        logger.info("")

        return {
            "registered": registered,
            "total": len(registered),
            "autohotkey_script": str(self.data_dir / "global_shortcuts.ahk")
        }

    def _generate_autohotkey_script(self):
        """Generate AutoHotkey script for global Windows shortcuts"""
        script_path = self.data_dir / "global_shortcuts.ahk"

        script_content = [
            "; Global Keyboard Shortcuts for Windows",
            "; Generated by LUMINA @ASK Integration",
            f"; Generated: {datetime.now().isoformat()}",
            "",
            "#NoEnv",
            "#SingleInstance Force",
            "",
            "; Cursor IDE Shortcuts (when Cursor is active)",
            ""
        ]

        # Add Windows global shortcuts (these work across all applications)
        if "windows_global" in self.shortcuts:
            script_content.append("; Windows Global Shortcuts (Works in All Applications)")
            script_content.append("")
            for key, action in self.shortcuts["windows_global"].items():
                ahk_key = self._convert_to_autohotkey(key)
                description = action.get("description", "")
                command = action.get("command", "")
                script_content.append(f"; {description}")
                script_content.append(f"{ahk_key}::{command}")
                script_content.append("")

        # Note: Cursor IDE shortcuts are configured in .cursor/keybindings.json
        script_content.append("; Note: Cursor IDE shortcuts are configured in .cursor/keybindings.json")
        script_content.append("; This script provides global Windows shortcuts that work in all applications")

        try:
            with open(script_path, 'w', encoding='utf-8') as f:
                f.write("\n".join(script_content))
            logger.info(f"   ✅ AutoHotkey script generated: {script_path.name}")
        except Exception as e:
            logger.error(f"   ❌ Error generating AutoHotkey script: {e}")

    def _convert_to_autohotkey(self, key: str) -> str:
        """Convert Cursor key format to AutoHotkey format"""
        # Convert ctrl+alt+u to ^!u format
        key = key.lower()
        key = key.replace("ctrl+", "^")
        key = key.replace("alt+", "!")
        key = key.replace("shift+", "+")
        key = key.replace("win+", "#")
        return key

    def install_autohotkey_shortcuts(self) -> Dict[str, Any]:
        """
        Install AutoHotkey shortcuts (requires AutoHotkey to be installed)

        Returns:
            Installation result
        """
        script_path = self.data_dir / "global_shortcuts.ahk"

        if not script_path.exists():
            logger.error("   ❌ AutoHotkey script not found")
            return {"installed": False, "error": "Script not found"}

        try:
            # Check if AutoHotkey is installed
            result = subprocess.run(
                ["where", "autohotkey"],
                capture_output=True,
                text=True
            )

            if result.returncode != 0:
                logger.warning("   ⚠️  AutoHotkey not found in PATH")
                logger.info("   📋 To install AutoHotkey shortcuts:")
                logger.info(f"      1. Install AutoHotkey from https://www.autohotkey.com/")
                logger.info(f"      2. Run: autohotkey {script_path}")
                return {
                    "installed": False,
                    "error": "AutoHotkey not installed",
                    "instructions": "Install AutoHotkey and run the script"
                }

            # Run AutoHotkey script
            subprocess.Popen(["autohotkey", str(script_path)])
            logger.info("   ✅ AutoHotkey shortcuts installed")

            return {
                "installed": True,
                "script": str(script_path)
            }
        except Exception as e:
            logger.error(f"   ❌ Error installing AutoHotkey shortcuts: {e}")
            return {"installed": False, "error": str(e)}


def main():
    """CLI interface"""
    import argparse

    parser = argparse.ArgumentParser(description="Global Keyboard Shortcuts for Windows - @ASK Integration")
    parser.add_argument("--register-cursor", action="store_true", help="Register Cursor IDE shortcuts")
    parser.add_argument("--register-windows", action="store_true", help="Register Windows global shortcuts")
    parser.add_argument("--install", action="store_true", help="Install AutoHotkey shortcuts")
    parser.add_argument("--generate", action="store_true", help="Generate AutoHotkey script")

    args = parser.parse_args()

    gks = GlobalKeyboardShortcutsWindows()

    if args.register_cursor:
        # Register Cursor IDE shortcuts
        cursor_shortcuts = {
            "workbench.action.sourceControl.discardAll": "ctrl+alt+u",
            "git.stageAll": "ctrl+alt+k"
        }
        gks.register_cursor_shortcuts(cursor_shortcuts)
    elif args.register_windows:
        # Register Windows global shortcuts
        windows_shortcuts = {
            "ctrl+alt+u": {
                "description": "Undo All Changes (Global)",
                "command": "Send, ^!u"
            },
            "ctrl+alt+k": {
                "description": "Keep All Changes (Global)",
                "command": "Send, ^!k"
            }
        }
        gks.register_windows_global_shortcuts(windows_shortcuts)
    elif args.generate:
        gks._generate_autohotkey_script()
    elif args.install:
        gks.install_autohotkey_shortcuts()
    else:
        parser.print_help()

    return 0


if __name__ == "__main__":


    sys.exit(main())