#!/usr/bin/env python3
"""
Helpdesk Ticket N8N Notifications

Sends notifications for EVERY ticket generated by internal helpdesk through:
- Email via @N8N@NAS MailPlus/DSM package
- SMS via @N8N
- Telegram via @N8N
- Discord via @N8N
- Slack via @N8N (future - when hiring more humans/volunteers)

Tags: #HELPDESK #N8N #NOTIFICATIONS #EMAIL #SMS #TELEGRAM #DISCORD #SLACK #REQUIRED @N8N @NAS @JARVIS @LUMINA @REC
"""

import sys
import json
import requests
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime

script_dir = Path(__file__).parent
project_root = script_dir.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
if str(script_dir) not in sys.path:
    sys.path.insert(0, str(script_dir))

try:
    from lumina_logger import get_logger
except ImportError:
    import logging
    logging.basicConfig(level=logging.INFO)
    get_logger = lambda name: logging.getLogger(name)

logger = get_logger("HelpdeskTicketN8NNotifications")

try:
    from jarvis_helpdesk_ticket_system import JARVISHelpdeskTicketSystem
    from unified_secrets_manager import UnifiedSecretsManager, SecretSource
    SYSTEMS_AVAILABLE = True
except ImportError as e:
    SYSTEMS_AVAILABLE = False
    logger.warning(f"Systems not available: {e}")


class HelpdeskTicketN8NNotifications:
    """
    Helpdesk Ticket N8N Notification System

    Sends notifications for EVERY ticket via:
    - Email (N8N@NAS MailPlus)
    - SMS (N8N)
    - Telegram (N8N)
    - Discord (N8N)
    - Slack (N8N - future)
    """

    def __init__(self, project_root: Optional[Path] = None):
        """Initialize N8N notification system"""
        if project_root is None:
            project_root = Path(__file__).parent.parent.parent

        self.project_root = Path(project_root)
        self.config_dir = self.project_root / "config"

        # N8N Configuration
        self.n8n_host = "<NAS_PRIMARY_IP>"
        self.n8n_port = 5678
        self.n8n_base_url = f"http://{self.n8n_host}:{self.n8n_port}"
        self.webhook_base = f"{self.n8n_base_url}/webhook"

        # Initialize systems
        if SYSTEMS_AVAILABLE:
            self.ticket_system = JARVISHelpdeskTicketSystem(project_root)
            try:
                self.secrets_manager = UnifiedSecretsManager(project_root)
            except:
                self.secrets_manager = None
        else:
            self.ticket_system = None
            self.secrets_manager = None

        # Notification channels
        self.channels = {
            "email": {
                "enabled": True,
                "webhook": f"{self.webhook_base}/helpdesk/email",
                "description": "Email via N8N@NAS MailPlus/DSM"
            },
            "sms": {
                "enabled": True,
                "webhook": f"{self.webhook_base}/helpdesk/sms",
                "description": "SMS via N8N"
            },
            "telegram": {
                "enabled": True,
                "webhook": f"{self.webhook_base}/helpdesk/telegram",
                "description": "Telegram via N8N"
            },
            "discord": {
                "enabled": True,
                "webhook": f"{self.webhook_base}/helpdesk/discord",
                "description": "Discord via N8N"
            },
            "slack": {
                "enabled": False,  # Future - when hiring more humans/volunteers
                "webhook": f"{self.webhook_base}/helpdesk/slack",
                "description": "Slack via N8N (future)"
            }
        }

        logger.info("=" * 80)
        logger.info("📧 HELPDESK TICKET N8N NOTIFICATIONS")
        logger.info("=" * 80)
        logger.info("   Email: N8N@NAS MailPlus/DSM")
        logger.info("   SMS: N8N")
        logger.info("   Telegram: N8N")
        logger.info("   Discord: N8N")
        logger.info("   Slack: N8N (future - when hiring more humans/volunteers)")
        logger.info("=" * 80)

    def send_ticket_notification(self, ticket: Dict[str, Any]) -> Dict[str, Any]:
        """
        Send notification for a ticket via all enabled channels

        Args:
            ticket: Ticket data dictionary

        Returns:
            Results dictionary with status for each channel
        """
        ticket_id = ticket.get("ticket_id", "UNKNOWN")
        results = {
            "ticket_id": ticket_id,
            "timestamp": datetime.now().isoformat(),
            "channels": {}
        }

        logger.info("=" * 80)
        logger.info(f"📧 SENDING NOTIFICATIONS FOR TICKET: {ticket_id}")
        logger.info("=" * 80)

        # Prepare notification payload
        payload = self._prepare_notification_payload(ticket)

        # Send to each enabled channel
        for channel_name, channel_config in self.channels.items():
            if not channel_config["enabled"]:
                logger.info(f"⏭️  {channel_name.upper()}: Disabled (future)")
                results["channels"][channel_name] = {
                    "status": "disabled",
                    "message": "Channel disabled (future)"
                }
                continue

            try:
                logger.info(f"📤 Sending to {channel_name.upper()}...")
                success = self._send_to_n8n_webhook(
                    channel_config["webhook"],
                    payload,
                    channel_name
                )

                results["channels"][channel_name] = {
                    "status": "success" if success else "failed",
                    "webhook": channel_config["webhook"],
                    "description": channel_config["description"]
                }

                if success:
                    logger.info(f"✅ {channel_name.upper()}: Sent successfully")
                else:
                    logger.warning(f"⚠️  {channel_name.upper()}: Failed")

            except Exception as e:
                logger.error(f"❌ {channel_name.upper()}: Error - {e}")
                results["channels"][channel_name] = {
                    "status": "error",
                    "error": str(e)
                }

        logger.info("=" * 80)
        return results

    def _prepare_notification_payload(self, ticket: Dict[str, Any]) -> Dict[str, Any]:
        """Prepare notification payload from ticket data"""
        team_assignment = ticket.get("team_assignment", {})

        payload = {
            "ticket_id": ticket.get("ticket_id", ""),
            "title": ticket.get("title", ""),
            "description": ticket.get("description", ""),
            "status": ticket.get("status", "open"),
            "priority": ticket.get("priority", "medium"),
            "category": ticket.get("category", ""),
            "created_at": ticket.get("created_at", ""),
            "created_by": ticket.get("created_by", ""),
            "team": {
                "team_id": team_assignment.get("team_id", ""),
                "team_name": team_assignment.get("team_name", ""),
                "division": team_assignment.get("division", ""),
                "team_manager": team_assignment.get("team_manager", ""),
                "technical_lead": team_assignment.get("technical_lead", ""),
                "primary_assignee": team_assignment.get("primary_assignee", "")
            },
            "metadata": ticket.get("metadata", {}),
            "notification_type": "ticket_created",
            "notification_timestamp": datetime.now().isoformat()
        }

        return payload

    def _send_to_n8n_webhook(
        self,
        webhook_url: str,
        payload: Dict[str, Any],
        channel_name: str
    ) -> bool:
        """
        Send payload to N8N webhook

        Args:
            webhook_url: N8N webhook URL
            payload: Notification payload
            channel_name: Channel name for logging

        Returns:
            True if successful
        """
        try:
            response = requests.post(
                webhook_url,
                json=payload,
                headers={"Content-Type": "application/json"},
                timeout=10
            )

            if response.status_code in [200, 201, 202]:
                logger.debug(f"✅ {channel_name}: N8N webhook responded {response.status_code}")
                return True
            else:
                logger.warning(f"⚠️  {channel_name}: N8N webhook returned {response.status_code}")
                return False

        except requests.exceptions.ConnectionError:
            logger.warning(f"⚠️  {channel_name}: Cannot connect to N8N at {webhook_url}")
            return False
        except requests.exceptions.Timeout:
            logger.warning(f"⚠️  {channel_name}: N8N webhook timeout")
            return False
        except Exception as e:
            logger.error(f"❌ {channel_name}: Error sending to N8N - {e}")
            return False

    def monitor_and_notify_new_tickets(self):
        """
        Monitor for new tickets and send notifications

        This should be called after ticket creation
        """
        if not self.ticket_system:
            logger.error("❌ Ticket system not available")
            return

        tickets_dir = self.ticket_system.tickets_dir
        processed_file = self.project_root / "data" / "helpdesk" / "n8n_notifications" / "processed_tickets.json"
        processed_file.parent.mkdir(parents=True, exist_ok=True)

        # Load processed tickets
        processed_tickets = set()
        if processed_file.exists():
            try:
                with open(processed_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    processed_tickets = set(data.get("processed_tickets", []))
            except:
                pass

        # Find new tickets
        new_tickets = []
        for ticket_file in tickets_dir.glob("*.json"):
            try:
                with open(ticket_file, 'r', encoding='utf-8') as f:
                    ticket = json.load(f)

                ticket_id = ticket.get("ticket_id")
                if ticket_id and ticket_id not in processed_tickets:
                    new_tickets.append(ticket)
            except Exception as e:
                logger.debug(f"Error reading ticket {ticket_file}: {e}")

        # Send notifications for new tickets
        for ticket in new_tickets:
            ticket_id = ticket.get("ticket_id")
            logger.info(f"📧 New ticket detected: {ticket_id}")

            results = self.send_ticket_notification(ticket)

            # Mark as processed
            processed_tickets.add(ticket_id)

        # Save processed tickets
        with open(processed_file, 'w', encoding='utf-8') as f:
            json.dump({
                "last_updated": datetime.now().isoformat(),
                "processed_tickets": list(processed_tickets)
            }, f, indent=2)

        if new_tickets:
            logger.info(f"✅ Processed {len(new_tickets)} new tickets")
        else:
            logger.debug("ℹ️  No new tickets to process")


def integrate_with_ticket_system():
    """
    Integrate notification system with ticket creation

    This function should be called when a ticket is created
    """
    notifications = HelpdeskTicketN8NNotifications()

    # Monitor for new tickets
    notifications.monitor_and_notify_new_tickets()

    return notifications


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Helpdesk Ticket N8N Notifications")
    parser.add_argument("--monitor", action="store_true", help="Monitor for new tickets")
    parser.add_argument("--test", action="store_true", help="Send test notification")
    parser.add_argument("--enable-slack", action="store_true", help="Enable Slack notifications")
    args = parser.parse_args()

    notifications = HelpdeskTicketN8NNotifications()

    if args.enable_slack:
        notifications.channels["slack"]["enabled"] = True
        logger.info("✅ Slack notifications enabled")

    if args.test:
        # Create test ticket
        test_ticket = {
            "ticket_id": "TEST-001",
            "title": "Test Ticket Notification",
            "description": "This is a test notification for N8N integration",
            "status": "open",
            "priority": "medium",
            "category": "test",
            "created_at": datetime.now().isoformat(),
            "created_by": "system",
            "team_assignment": {
                "team_id": "test_team",
                "team_name": "Test Team",
                "division": "Testing"
            }
        }

        results = notifications.send_ticket_notification(test_ticket)
        print(json.dumps(results, indent=2))

    if args.monitor:
        logger.info("🔄 Starting ticket monitoring...")
        import time
        while True:
            notifications.monitor_and_notify_new_tickets()
            time.sleep(60)  # Check every minute
