#!/usr/bin/env python3
"""
JARVIS: Enhance Sequential Storytelling

Enhances the sequential storytelling with better narrative flow,
thematic grouping, and lucid connections between asks.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional
from collections import defaultdict
import logging
logger = logging.getLogger("jarvis_enhance_storytelling")


def enhance_storytelling(project_root: Path):
    try:
        """
        Enhance the sequential storytelling with better narrative
        """
        print("="*80)
        print("📖 JARVIS: Enhancing Sequential Storytelling")
        print("="*80)

        intelligence_dir = project_root / "data" / "intelligence"
        asks_file = intelligence_dir / "LUMINA_ALL_ASKS_ORDERED.json"

        if not asks_file.exists():
            print(f"❌ Ordered asks file not found: {asks_file}")
            return

        # Load ordered asks
        with open(asks_file, 'r', encoding='utf-8') as f:
            data = json.load(f)

        asks = data.get("asks", [])
        print(f"\n📊 Processing {len(asks)} asks...")

        # Group by themes and create narrative
        enhanced_story = create_enhanced_storytelling(asks)

        # Save enhanced storytelling
        enhanced_file = intelligence_dir / "LUMINA_ENHANCED_STORYTELLING.md"
        with open(enhanced_file, 'w', encoding='utf-8') as f:
            f.write(enhanced_story)

        print(f"\n✅ Enhanced storytelling saved: {enhanced_file.name}")
        print("\n" + "="*80)
        print("✅ ENHANCEMENT COMPLETE")
        print("="*80)

        return enhanced_file

    except Exception as e:
        logger.error(f"Error in enhance_storytelling: {e}", exc_info=True)
        raise
def create_enhanced_storytelling(asks: List[Dict[str, Any]]) -> str:
    """Create enhanced storytelling with thematic grouping"""

    story = []
    story.append("# 📖 LUMINA PROJECT: Enhanced Sequential Storytelling")
    story.append("")
    story.append("**Generated by:** JARVIS Enhanced Storytelling System")
    story.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    story.append(f"**Total @ASKS:** {len(asks)}")
    story.append("")
    story.append("---")
    story.append("")
    story.append("## 🎬 Prologue: The Journey Begins")
    story.append("")
    story.append("This is the story of Lumina - from its inception as an AI experiment to its evolution into an enterprise-grade platform. Each @ASK represents a step in this journey, a question asked, a problem solved, a capability enhanced.")
    story.append("")
    story.append("---")
    story.append("")

    # Group asks by major themes
    themes = group_asks_by_themes(asks)

    chapter_num = 1
    for theme_name, theme_asks in themes.items():
        story.append(f"## 📚 Chapter {chapter_num}: {theme_name}")
        story.append("")
        story.append(f"*{len(theme_asks)} @ASKS in this chapter*")
        story.append("")

        # Create narrative flow within theme
        narrative = create_theme_narrative(theme_name, theme_asks)
        story.append(narrative)
        story.append("")
        story.append("---")
        story.append("")

        chapter_num += 1

    story.append("## 🏁 Epilogue: The Story Continues")
    story.append("")
    story.append("Lumina's story is not complete. It continues to evolve, to learn, to grow. Each new @ASK adds another chapter, another layer of capability, another step toward the vision.")
    story.append("")
    story.append(f"**Total @ASKS Processed:** {len(asks)}")
    story.append(f"**Last Updated:** {datetime.now().isoformat()}")
    story.append("")
    story.append("---")
    story.append("")
    story.append("*This is a living document. The story continues.*")

    return "\n".join(story)

def group_asks_by_themes(asks: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """Group asks by major themes"""
    themes = defaultdict(list)

    for ask in asks:
        category = ask.get("category", "general")
        ask_text = ask.get("ask_text", "").lower()

        # Determine major theme
        theme = determine_major_theme(category, ask_text)
        themes[theme].append(ask)

    # Sort themes by chronological order of first ask
    theme_order = {
        "Foundation & Architecture": 1,
        "Core Systems Development": 2,
        "Intelligence & SYPHON": 3,
        "AI Capabilities & Agents": 4,
        "Quality & Verification": 5,
        "Integration & Orchestration": 6,
        "Enhancement & Optimization": 7,
        "Analysis & Learning": 8,
        "Documentation & Communication": 9,
        "Current Development": 10
    }

    sorted_themes = sorted(themes.items(), key=lambda x: (
        theme_order.get(x[0], 99),
        min((ask.get("timestamp", "") for ask in x[1]), default="")
    ))

    return dict(sorted_themes)

def determine_major_theme(category: str, ask_text: str) -> str:
    """Determine major theme from category and text"""

    # Foundation themes
    if any(keyword in ask_text for keyword in ["beginning", "start", "foundation", "base", "core", "architecture"]):
        return "Foundation & Architecture"

    # Core systems
    if category in ["system", "development"] or any(keyword in ask_text for keyword in ["workflow", "orchestration", "base", "core"]):
        return "Core Systems Development"

    # Intelligence
    if category == "intelligence" or any(keyword in ask_text for keyword in ["syphon", "extract", "intelligence", "gather"]):
        return "Intelligence & SYPHON"

    # AI capabilities
    if category == "ai" or any(keyword in ask_text for keyword in ["ai", "agent", "llm", "anthropic", "claude", "gpt", "model"]):
        return "AI Capabilities & Agents"

    # Quality
    if category in ["fix", "testing"] or any(keyword in ask_text for keyword in ["fix", "bug", "error", "test", "verify", "quality", "shrink", "confidence"]):
        return "Quality & Verification"

    # Integration
    if category == "integration" or any(keyword in ask_text for keyword in ["integrate", "connect", "sync", "link"]):
        return "Integration & Orchestration"

    # Enhancement
    if category == "enhancement" or any(keyword in ask_text for keyword in ["enhance", "improve", "optimize", "upgrade"]):
        return "Enhancement & Optimization"

    # Analysis
    if category == "analysis" or any(keyword in ask_text for keyword in ["analyze", "compare", "study", "review", "examine"]):
        return "Analysis & Learning"

    # Documentation
    if category == "documentation" or any(keyword in ask_text for keyword in ["document", "write", "readme", "doc"]):
        return "Documentation & Communication"

    # Default to current
    return "Current Development"

def create_theme_narrative(theme_name: str, theme_asks: List[Dict[str, Any]]) -> str:
    """Create narrative flow for a theme"""
    narrative = []

    # Sort asks chronologically within theme
    sorted_asks = sorted(theme_asks, key=lambda x: x.get("timestamp", ""))

    # Create introduction
    narrative.append(f"### The {theme_name} Journey")
    narrative.append("")

    # Group by sub-themes if many asks
    if len(sorted_asks) > 10:
        sub_themes = group_by_sub_themes(sorted_asks)
        for sub_theme, sub_asks in sub_themes.items():
            narrative.append(f"#### {sub_theme}")
            narrative.append("")
            for ask in sub_asks[:5]:  # Limit to top 5 per sub-theme
                narrative.append(f"- **{ask.get('ask_text', 'N/A')[:150]}...**")
                narrative.append(f"  - *Priority: {ask.get('priority', 'normal')} | Source: {ask.get('source', 'unknown')}*")
                narrative.append("")
    else:
        # Show all asks for smaller themes
        for i, ask in enumerate(sorted_asks, 1):
            narrative.append(f"#### {i}. {ask.get('ask_text', 'N/A')[:200]}")
            narrative.append("")
            narrative.append(f"**Details:**")
            narrative.append(f"- Priority: {ask.get('priority', 'normal').upper()}")
            narrative.append(f"- Category: {ask.get('category', 'general')}")
            narrative.append(f"- Source: {ask.get('source', 'unknown')}")
            narrative.append(f"- Timestamp: {ask.get('timestamp', 'unknown')}")
            narrative.append("")

    return "\n".join(narrative)

def group_by_sub_themes(asks: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """Group asks by sub-themes"""
    sub_themes = defaultdict(list)

    for ask in asks:
        category = ask.get("category", "general")
        sub_themes[category].append(ask)

    return dict(sub_themes)

if __name__ == "__main__":
    project_root = Path(__file__).parent.parent.parent
    enhance_storytelling(project_root)

